Cufon.replace('.asMelhores');
Cufon.replace('#recebaOfertas label');
Cufon.replace('#recebaOfertas button');
Cufon.replace('#logar h2');
Cufon.replace('#innerLogar button');
Cufon.replace('#ofertaDia h2');
Cufon.replace('.socialOferta li.compartilhe');
Cufon.replace('#quantidadeOferta h3');
Cufon.replace('#sejaParceiro h2');
Cufon.replace('#sejaParceiro a');
Cufon.replace('#recomendar .info');
Cufon.replace('#twitter .lkn-siga');
Cufon.replace('#facebook h3');
Cufon.replace('.paginas h2');
Cufon.replace('.paginas h3');
Cufon.replace('.cadastro-ok h3');